version: "3.3"

services:
  db:
    build:
      context: db
      dockerfile: Dockerfile
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: maintony
      POSTGRES_USER: anthony
      POSTGRES_PASSWORD: anthony
    ports:
      - "5432"
  app:
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    environment:
      PGHOST: db
      PGDATABASE: maintony
      PGUSER: anthony
      PGPASSWORD: anthony
      JWT_SECRET: I-Love-KFC-Hot-Crispy-Chicken-Bucket-9-Pcs
    depends_on:
      - db
    ports:
      - "9101:3000"
