version: "3.3"

services:
  db:
    build:
      context: db
      dockerfile: Dockerfile
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: maintony
      POSTGRES_USER: anthony
      POSTGRES_PASSWORD: anthony
    ports:
      - "9100:5432"
  app:
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file:
      - ./app/.env
    environment:
      PGHOST: db
      PGDATABASE: maintony
      PGUSER: anthony
      PGPASSWORD: anthony
      NEXT_PUBLIC_BASE_URL: http://localhost:9101
    depends_on:
      - db
    ports:
      - "9101:3000"
